// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P5WebApp.Data;

#nullable disable

namespace P5WebApp.Migrations
{
    [DbContext(typeof(P5Referential))]
    [Migration("20260627165859_Migration202606275")]
    partial class Migration202606275
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BrandFinishType", b =>
                {
                    b.Property<int>("BrandsBrandId")
                        .HasColumnType("int");

                    b.Property<int>("FinishTypesFinishTypeId")
                        .HasColumnType("int");

                    b.HasKey("BrandsBrandId", "FinishTypesFinishTypeId");

                    b.HasIndex("FinishTypesFinishTypeId");

                    b.ToTable("BrandFinishType");
                });

            modelBuilder.Entity("CarModelFinishType", b =>
                {
                    b.Property<int>("CarModelsId")
                        .HasColumnType("int");

                    b.Property<int>("FinishTypesFinishTypeId")
                        .HasColumnType("int");

                    b.HasKey("CarModelsId", "FinishTypesFinishTypeId");

                    b.HasIndex("FinishTypesFinishTypeId");

                    b.ToTable("CarModelFinishType");
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.PrimitiveCollection<string>("AssociatedFixIds")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("AssociatedPhotoIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CarAddAvailabilityDate")
                        .HasColumnType("date");

                    b.Property<int>("CarBrandId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CarBuyDate")
                        .HasColumnType("date");

                    b.Property<double>("CarBuyPrice")
                        .HasColumnType("float");

                    b.Property<DateOnly?>("CarDateSold")
                        .HasColumnType("date");

                    b.Property<string>("CarDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarFinishTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CarModelId")
                        .HasColumnType("int");

                    b.Property<bool>("CarPublished")
                        .HasColumnType("bit");

                    b.Property<double>("CarSellingPrice")
                        .HasColumnType("float");

                    b.Property<string>("CarVinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("CarYear")
                        .HasColumnType("date");

                    b.HasKey("CarId");

                    b.ToTable("Cars", (string)null);
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.CarModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssociatedBrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedBrandId");

                    b.ToTable("CarModels", (string)null);
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.FinishType", b =>
                {
                    b.Property<int>("FinishTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinishTypeId"));

                    b.PrimitiveCollection<string>("AssociatedBrandsIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("AssociatedCarModelIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinishTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FinishTypeId");

                    b.ToTable("FinishTypes", (string)null);
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.Fix", b =>
                {
                    b.Property<int>("FixId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FixId"));

                    b.Property<int>("AssociatedCarId")
                        .HasColumnType("int");

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<double>("FixCost")
                        .HasColumnType("float");

                    b.Property<DateOnly?>("FixDate")
                        .HasColumnType("date");

                    b.Property<string>("FixDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FixId");

                    b.HasIndex("CarId");

                    b.ToTable("Fixes", (string)null);
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<int>("AssociatedCarId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhotoId");

                    b.ToTable("Photos", (string)null);
                });

            modelBuilder.Entity("BrandFinishType", b =>
                {
                    b.HasOne("P5WebApp.Models.Entities.Brand", null)
                        .WithMany()
                        .HasForeignKey("BrandsBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P5WebApp.Models.Entities.FinishType", null)
                        .WithMany()
                        .HasForeignKey("FinishTypesFinishTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarModelFinishType", b =>
                {
                    b.HasOne("P5WebApp.Models.Entities.CarModel", null)
                        .WithMany()
                        .HasForeignKey("CarModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P5WebApp.Models.Entities.FinishType", null)
                        .WithMany()
                        .HasForeignKey("FinishTypesFinishTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.CarModel", b =>
                {
                    b.HasOne("P5WebApp.Models.Entities.Brand", "AssociatedBrand")
                        .WithMany("CarModels")
                        .HasForeignKey("AssociatedBrandId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AssociatedBrand");
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.Fix", b =>
                {
                    b.HasOne("P5WebApp.Models.Entities.Car", null)
                        .WithMany("CarFixesList")
                        .HasForeignKey("CarId");
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.Brand", b =>
                {
                    b.Navigation("CarModels");
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.Car", b =>
                {
                    b.Navigation("CarFixesList");
                });
#pragma warning restore 612, 618
        }
    }
}
