// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P5WebApp.Data;

#nullable disable

namespace P5WebApp.Migrations
{
    [DbContext(typeof(P5Referential))]
    [Migration("20260521090720_Migration5052126")]
    partial class Migration5052126
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("P5WebApp.Models.Entities.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<int>("AssociatedShortAddId")
                        .HasColumnType("int");

                    b.Property<int?>("BrandCarId")
                        .HasColumnType("int");

                    b.Property<int>("CarBrandId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CarBuyDate")
                        .HasColumnType("date");

                    b.Property<double>("CarBuyPrice")
                        .HasColumnType("float");

                    b.Property<int>("CarFinishTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CarModelId")
                        .HasColumnType("int");

                    b.Property<string>("CarVinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CarYear")
                        .HasColumnType("date");

                    b.HasKey("CarId");

                    b.HasIndex("AssociatedShortAddId")
                        .IsUnique();

                    b.HasIndex("BrandCarId");

                    b.HasIndex("CarId")
                        .IsUnique();

                    b.HasIndex("CarModelId");

                    b.ToTable("Cars", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.ShortAdd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ShortAddAvailabilityDate")
                        .HasColumnType("date");

                    b.Property<double>("ShortAddBuyPrice")
                        .HasColumnType("float");

                    b.Property<int>("ShortAddCarId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ShortAddDateSold")
                        .HasColumnType("date");

                    b.Property<double>("ShortAddSellingPrice")
                        .HasColumnType("float");

                    b.Property<bool>("ShortAddSold")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ShortAdds", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.Brand", b =>
                {
                    b.HasBaseType("P5WebApp.Models.Entities.Car");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("BrandId");

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.CarModel", b =>
                {
                    b.HasBaseType("P5WebApp.Models.Entities.Car");

                    b.Property<int>("AsociatedBrandId")
                        .HasColumnType("int");

                    b.Property<int?>("FinishTypeCarId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AsociatedBrandId");

                    b.HasIndex("FinishTypeCarId");

                    b.HasIndex("Id");

                    b.ToTable("Models", (string)null);
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.FinishType", b =>
                {
                    b.HasBaseType("P5WebApp.Models.Entities.Car");

                    b.Property<int>("AssociatedBrandId")
                        .HasColumnType("int");

                    b.Property<int>("AssociatedCarId")
                        .HasColumnType("int");

                    b.Property<int>("AssociatedCarModelId")
                        .HasColumnType("int");

                    b.Property<int>("FinishTypeCarId")
                        .HasColumnType("int");

                    b.Property<int>("FinishTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FinishTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AssociatedBrandId")
                        .IsUnique()
                        .HasFilter("[AssociatedBrandId] IS NOT NULL");

                    b.HasIndex("AssociatedCarId");

                    b.HasIndex("AssociatedCarModelId")
                        .IsUnique()
                        .HasFilter("[AssociatedCarModelId] IS NOT NULL");

                    b.HasIndex("FinishTypeCarId");

                    b.HasIndex("FinishTypeId");

                    b.ToTable("FinishTypes", (string)null);
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.Fix", b =>
                {
                    b.HasBaseType("P5WebApp.Models.Entities.Car");

                    b.Property<int>("AssociatedCarId")
                        .HasColumnType("int");

                    b.Property<int>("FinishTypeCarId")
                        .HasColumnType("int");

                    b.Property<double>("FixCost")
                        .HasColumnType("float");

                    b.Property<DateOnly>("FixDate")
                        .HasColumnType("date");

                    b.Property<string>("FixDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FixId")
                        .HasColumnType("int");

                    b.HasIndex("AssociatedCarId");

                    b.HasIndex("FinishTypeCarId");

                    b.HasIndex("FixId");

                    b.ToTable("Fixes", (string)null);
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.Photo", b =>
                {
                    b.HasBaseType("P5WebApp.Models.Entities.ShortAdd");

                    b.Property<int>("AssociatedShortAddId")
                        .HasColumnType("int");

                    b.Property<int>("PhotoId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AssociatedShortAddId");

                    b.ToTable("Photos", (string)null);
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.Car", b =>
                {
                    b.HasOne("P5WebApp.Models.Entities.ShortAdd", "AssociatedShortAdd")
                        .WithOne("Car")
                        .HasForeignKey("P5WebApp.Models.Entities.Car", "AssociatedShortAddId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P5WebApp.Models.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandCarId");

                    b.HasOne("P5WebApp.Models.Entities.CarModel", "CarModel")
                        .WithMany()
                        .HasForeignKey("CarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociatedShortAdd");

                    b.Navigation("Brand");

                    b.Navigation("CarModel");
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.Brand", b =>
                {
                    b.HasOne("P5WebApp.Models.Entities.Car", null)
                        .WithOne()
                        .HasForeignKey("P5WebApp.Models.Entities.Brand", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.CarModel", b =>
                {
                    b.HasOne("P5WebApp.Models.Entities.Brand", "AssociatedBrand")
                        .WithMany("CarModels")
                        .HasForeignKey("AsociatedBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P5WebApp.Models.Entities.Car", null)
                        .WithOne()
                        .HasForeignKey("P5WebApp.Models.Entities.CarModel", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P5WebApp.Models.Entities.FinishType", null)
                        .WithMany("CarModels")
                        .HasForeignKey("FinishTypeCarId");

                    b.Navigation("AssociatedBrand");
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.FinishType", b =>
                {
                    b.HasOne("P5WebApp.Models.Entities.Brand", "AssociatedBrand")
                        .WithOne("FinishType")
                        .HasForeignKey("P5WebApp.Models.Entities.FinishType", "AssociatedBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P5WebApp.Models.Entities.Car", "AssociatedCar")
                        .WithMany()
                        .HasForeignKey("AssociatedCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P5WebApp.Models.Entities.CarModel", "AssociatedCarModel")
                        .WithOne("FinishType")
                        .HasForeignKey("P5WebApp.Models.Entities.FinishType", "AssociatedCarModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P5WebApp.Models.Entities.Car", null)
                        .WithOne()
                        .HasForeignKey("P5WebApp.Models.Entities.FinishType", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P5WebApp.Models.Entities.FinishType", "FinishType")
                        .WithMany()
                        .HasForeignKey("FinishTypeCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociatedBrand");

                    b.Navigation("AssociatedCar");

                    b.Navigation("AssociatedCarModel");

                    b.Navigation("FinishType");
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.Fix", b =>
                {
                    b.HasOne("P5WebApp.Models.Entities.Car", "AssociatedCar")
                        .WithMany("CarFixesList")
                        .HasForeignKey("AssociatedCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P5WebApp.Models.Entities.Car", null)
                        .WithOne()
                        .HasForeignKey("P5WebApp.Models.Entities.Fix", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P5WebApp.Models.Entities.FinishType", "FinishType")
                        .WithMany()
                        .HasForeignKey("FinishTypeCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociatedCar");

                    b.Navigation("FinishType");
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.Photo", b =>
                {
                    b.HasOne("P5WebApp.Models.Entities.ShortAdd", "AssociatedShortAdd")
                        .WithMany("ShortAddPhotosList")
                        .HasForeignKey("AssociatedShortAddId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("P5WebApp.Models.Entities.ShortAdd", null)
                        .WithOne()
                        .HasForeignKey("P5WebApp.Models.Entities.Photo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociatedShortAdd");
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.Car", b =>
                {
                    b.Navigation("CarFixesList");
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.ShortAdd", b =>
                {
                    b.Navigation("Car")
                        .IsRequired();

                    b.Navigation("ShortAddPhotosList");
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.Brand", b =>
                {
                    b.Navigation("CarModels");

                    b.Navigation("FinishType")
                        .IsRequired();
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.CarModel", b =>
                {
                    b.Navigation("FinishType")
                        .IsRequired();
                });

            modelBuilder.Entity("P5WebApp.Models.Entities.FinishType", b =>
                {
                    b.Navigation("CarModels");
                });
#pragma warning restore 612, 618
        }
    }
}
